# TensorFlow Basics

In [1]:
import tensorflow as tf

In [2]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

2.1.0


## Tensors

In [11]:
hello = tf.constant('Hello ')

In [12]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [13]:
world = tf.constant('World')

In [14]:
result = hello + world

In [15]:
result

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World'>

In [16]:
type(result)

tensorflow.python.framework.ops.EagerTensor

In [17]:
tf.print(result)

Hello World


In [18]:
result

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World'>

** Computations **

In [19]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [20]:
type(tensor_1)

tensorflow.python.framework.ops.EagerTensor

In [21]:
tensor_1 + tensor_2

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [22]:
sess

In [23]:
sess.close()

## Operations

In [24]:
const = tf.constant(10)

In [25]:
fill_mat = tf.fill((4,4),10)

In [26]:
myzeros = tf.zeros((4,4))

In [27]:
myones = tf.ones((4,4))

In [28]:
myrandn = tf.random.normal((4,4),mean=0,stddev=0.5)

In [29]:
myrandu = tf.random.uniform((4,4),minval=0,maxval=1)

In [30]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [31]:
# Only run this cell once!
sess = tf.compat.v1.InteractiveSession()

In [32]:
for op in my_ops:
    print(op.eval())
    print('\n')

NotImplementedError: eval is not supported when eager execution is enabled, is .numpy() what you're looking for?

## Matrix Multiplication

In [ ]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [ ]:
a.get_shape()

In [ ]:
b = tf.constant([[10],[100]])

In [ ]:
b.get_shape()

In [ ]:
result = tf.matmul(a,b)

In [ ]:
result.eval()