# SciKit Learn Preprocessing Overview

In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[97, 33],
       [79, 81],
       [28, 67],
       [87, 24],
       [ 5, 94],
       [26, 76],
       [88, 51],
       [42, 69],
       [50, 71],
       [19, 92]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
scaler_model.fit(data)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
scaler_model.transform(data)

array([[1.        , 0.12857143],
       [0.80434783, 0.81428571],
       [0.25      , 0.61428571],
       [0.89130435, 0.        ],
       [0.        , 1.        ],
       [0.22826087, 0.74285714],
       [0.90217391, 0.38571429],
       [0.40217391, 0.64285714],
       [0.48913043, 0.67142857],
       [0.15217391, 0.97142857]])

In [8]:
# In one step
result = scaler_model.fit_transform(data)

In [9]:
result

array([[1.        , 0.12857143],
       [0.80434783, 0.81428571],
       [0.25      , 0.61428571],
       [0.89130435, 0.        ],
       [0.        , 1.        ],
       [0.22826087, 0.74285714],
       [0.90217391, 0.38571429],
       [0.40217391, 0.64285714],
       [0.48913043, 0.67142857],
       [0.15217391, 0.97142857]])

In [10]:
import pandas as pd

In [11]:
data = pd.DataFrame(data=np.random.randint(0,101,(50,4)),columns=['f1','f2','f3','label'])

In [12]:
data.head()

f1   f2  f3  label
0  14    2  14     10
1  74   75  38     82
2  23   79  82     28
3  20   23  60     42
4  40  100  55     44

In [13]:
x = data[['f1','f2','f3']] # Alternatively x = data.drop('label',axis=1)
y = data['label']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [16]:
X_train.shape

(35, 3)

In [17]:
X_test.shape

(15, 3)

In [18]:
y_train.shape

(35,)

In [19]:
y_test.shape

(15,)

## Great Job!